### ISSUE TITLE
rss

### ISSUE THREAD

**Issue by tsvtt** [codemzy/static-blog#7]
Hi. Consider adding RSS to your blog so that people can subscribe to it and receive notifications when new posts get added.
Thanks for your blog. The articles about regex were useful to me.

**Comment by codemzy** [comment]
Great idea, I'll update this issue when it's added!

**Comment by codemzy** [comment]
Hey 👋 

I came to build this today and realised I already had an RSS feed, I just hadn't linked to it! It's here https://www.codemzy.com/blog/rss.xml

I've added a link in the top menu for now while I decide where best to link to it! 

Thanks 😅
